-- MySQL Script generated by MySQL Workbench
-- Mon Nov  8 14:27:04 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `user_db` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `user_db` DEFAULT CHARACTER SET utf8 ;
USE `user_db` ;

-- -----------------------------------------------------
-- Table `mydb`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_db`.`users_wip` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL UNIQUE,
  `role` VARCHAR(45) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO users_wip (id, name, role, password) VALUES
(1, 'admin', 'user', '1000:e017e58727620cf0ea5bdfaeb04760f8131c885f0c3bb8e0:117fdf12336b21ab12f3a195191a5986b556137c1408adb9');
