-- MySQL Script generated by MySQL Workbench
-- Mon Nov  8 14:27:04 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`article` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `price` DECIMAL(8,2) NULL,
  `description` TEXT NULL,
  `name` VARCHAR(45) NOT NULL,
  `quantity` INT NOT NULL DEFAULT 0,
  `link` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`article_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`article_category` (
  `idArticle` INT NOT NULL,
  `idCategory` INT NOT NULL,
  PRIMARY KEY (`idArticle`, `idCategory`),
  INDEX `fk_article_has_category_category1_idx` (`idCategory` ASC) VISIBLE,
  INDEX `fk_article_has_category_article_idx` (`idArticle` ASC) VISIBLE,
  CONSTRAINT `fk_article_has_category_article`
    FOREIGN KEY (`idArticle`)
    REFERENCES `mydb`.`article` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_article_has_category_category1`
    FOREIGN KEY (`idCategory`)
    REFERENCES `mydb`.`category` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cart` (
  `idArticle` INT NOT NULL,
  `idUser` INT NOT NULL,
  `quantity` INT NULL,
  PRIMARY KEY (`idArticle`, `idUser`),
  INDEX `fk_article_has_cart_cart1_idx` (`idUser` ASC) VISIBLE,
  INDEX `fk_article_has_cart_article1_idx` (`idArticle` ASC) VISIBLE,
  CONSTRAINT `fk_article_has_article_cart`
    FOREIGN KEY (`idArticle`)
    REFERENCES `mydb`.`article` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_article_has_user_cart`
    FOREIGN KEY (`idUser`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


INSERT INTO article (price, description, name, quantity) VALUES ('100', "Great quality hammer","Hammer", '4');
INSERT INTO article (price, description, name, quantity) VALUES ('59.90', "Great quality shovel","Shovel", '2');
INSERT INTO article (price, description, name, quantity) VALUES ('1.10', "Great quality nail","Nail", '4');

INSERT INTO category(name) VALUES("Tools");
INSERT INTO category(name) VALUES("Outdoor");
INSERT INTO category(name) VALUES("Single use");
INSERT INTO category(name) VALUES("Paint");
INSERT INTO category(name) VALUES("Electric tools");
INSERT INTO category(name) VALUES("Clothes");
INSERT INTO category(name) VALUES("Safety");

INSERT INTO article_category(idArticle, idCategory) VALUES('1','1');
INSERT INTO article_category(idArticle, idCategory) VALUES('1','2');
INSERT INTO article_category(idArticle, idCategory) VALUES('2','1');
INSERT INTO article_category(idArticle, idCategory) VALUES('2','2');
INSERT INTO article_category(idArticle, idCategory) VALUES('3','3');




