name: Continous deployement

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Open the tunnel
        run: |
          echo "${{ secrets.DMZKEY }}" > dmzkey.pem
          echo "${{ secrets.KEY }}" > key.pem
          sudo chmod 400 dmzkey.pem
          sudo chmod 400 key.pem
          sudo ssh -o StrictHostKeyChecking=no -f -N -L 23:10.0.1.20:22 -L 8082:10.0.1.20:8080 WORKINPROGRESS@16.170.194.237 -i ./dmzkey.pem
          
      - name: Transfer the file
        run: |
          sudo scp -o StrictHostKeyChecking=no -P 23 -i key.pem -r pom.xml admin@localhost:/home/admin/
          sudo scp -o StrictHostKeyChecking=no -P 23 -i key.pem -r src admin@localhost:/home/admin/
          sudo ssh -o StrictHostKeyChecking=no admin@localhost -p 23 -i ./key.pem mvn clean package tomcat7:redeploy
