# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Continuous integration

on:
  push:
    branches: [ feature/refactor-admin ]
  pull_request:
    branches: [ feature/refactor-admin ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: build&start containers with docker compose
        run: docker-compose -f "database/docker-compose.yml" up -d --build
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Test with Maven
        run: |
          mvn clean test